language: python
python:
- 3.6
- 3.5
- 3.4
install:
- pip install -U tox-travis
- pip install -r requirements/prod.txt
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: mattmacari
  password:
    secure: NMxa1Wmn1ssUkOo+/cKldHHC8PW19Saxcuf/md9BYV935MtBRUJdoBH8pn+ILCfbV6lu2WU8ET0bC1BcL0NAwDCiPgrDDGoHevhu1uKED9QYO2O+OGDFbFTNwFY2lEM1ZtiB3qJv5+QysIzT/MqioChBgGgrFwAIZy0wMeaDsbdUWWr1m8rWldndxGAXtcQ/6zK9paL4noBf/wfxzIVPG7czSslyXE+qDu/0mw52T5ok2p1jHaTAUMczw4adY1zbzfKk9KHXSBLjfz9E0tOe7EFrqcnGMdsG/GTXohzOE50CIlHaEKf2KRKg1lvQD0iC02oXOcrMTxBkP+qOldPsvX8jZNEBY1htrNBtjlou9464sLeYg6TPfVS8hQ92bPj5c7J5BKCK0OF+yLuRKHkTiv0qxWE3h4PQhFtxh8EECGD6/oDvU0u39ISf5lDZCybMfzEmlJ0Ra10v6HSb+9+GPedFxkf8CCnKJRO7NQUpolIDH3PidxoJkM8l1Y6DJwL09Z7ySiJRgDa1O0tL83yolUP5pWkATCoIrvIOveeFirsy8N6/NNXx7l/aeP5ykgRtlppQjE/g87B9zsx7zxe7yeiYlfXyY92bs0Z7f+eBP6vVQ/8B8tY66mtRnvwIfPavPCRPp9tHY4oRaYvYpz0YPg1X2rttlncuncMM2MJM2Sw=
  on:
    tags: true
    repo: mattmacari/usda_parser
    python: 3.6
